/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"
#include "IfxGeth_Eth.h"
#include "Configuration.h"
#include "ConfigurationIsr.h"
#include "Ifx_Lwip.h"
#include "Echo.h"
#include "UART_Logging.h"

#define UART_LOG(msg) sendUARTMessage((char *)(msg), (Ifx_SizeT)(sizeof(msg) - 1))

extern IfxCpu_syncEvent g_cpuSyncEvent;

void core2_main(void)
{
    uint32 lastLogTick = 0;
    uint8  lastLinkUp  = 0xFF;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initUART();
    UART_LOG("CPU2: entered core2_main\r\n");

    IfxStm_CompareConfig stmCompareConfig;                                  /* STM Configuration declaration                */

    IfxStm_initCompareConfig(&stmCompareConfig);                            /* Initialize a default configuration for STM   */

    stmCompareConfig.triggerPriority     = ISR_PRIORITY_OS_TICK;            /* Priority of the interrupt generated by STM   */
    stmCompareConfig.comparatorInterrupt = IfxStm_ComparatorInterrupt_ir0;  /* Select the request source 0                  */
    stmCompareConfig.ticks               = IFX_CFG_STM_TICKS_PER_MS * 10;   /* First interrupt shall occur after 10 ms      */
    stmCompareConfig.typeOfService       = IfxSrc_Tos_cpu2;                 /* CPU2 serves the interrupts                   */

    IfxStm_initCompare(&MODULE_STM0, &stmCompareConfig);                    /* Initialize the Compare functionality         */
    UART_LOG("CPU2: STM compare configured\r\n");

    IfxGeth_enableModule(&MODULE_GETH);                     /* Enable Gigabit Ethernet Media Access Controller (GETH) module*/
    UART_LOG("CPU2: GETH module enabled\r\n");

    /* Define a MAC Address */
    eth_addr_t ethAddr;
    ethAddr.addr[0] = 0xDE;
    ethAddr.addr[1] = 0xAD;
    ethAddr.addr[2] = 0xBE;
    ethAddr.addr[3] = 0xEF;
    ethAddr.addr[4] = 0xFE;
    ethAddr.addr[5] = 0xED;

    Ifx_Lwip_init(ethAddr);                                 /* Initialize LwIP with the MAC address                         */
    UART_LOG("CPU2: lwIP initialized\r\n");

    ip4_addr_t staticIp;
    ip4_addr_t staticNetmask;
    ip4_addr_t staticGateway;
    IP4_ADDR(&staticIp, 192, 168, 1, 100);
    IP4_ADDR(&staticNetmask, 255, 255, 255, 0);
    IP4_ADDR(&staticGateway, 192, 168, 1, 1);
    netif_set_addr(Ifx_Lwip_getNetIf(), &staticIp, &staticNetmask, &staticGateway);
    UART_LOG("CPU2: static IP set to 192.168.1.100\r\n");

    echoInit();                                             /* Initialize ECHO application                                  */
    UART_LOG("CPU2: echo server initialized\r\n");
    
    while(1)
    {
        Ifx_Lwip_pollTimerFlags();                          /* Poll LwIP timers and trigger protocols execution if required */
        Ifx_Lwip_pollReceiveFlags();                        /* Receive data package through ETH                             */

        {
            uint8 linkUp = (uint8)(netif_is_link_up(Ifx_Lwip_getNetIf()) ? 1U : 0U);
            if (linkUp != lastLinkUp)
            {
                lastLinkUp = linkUp;
                if (linkUp)
                {
                    UART_LOG("CPU2: Ethernet link is UP\r\n");
                }
                else
                {
                    UART_LOG("CPU2: Ethernet link is DOWN\r\n");
                }
            }

            if ((g_TickCount_1ms - lastLogTick) >= 1000U)
            {
                lastLogTick = g_TickCount_1ms;
                UART_LOG("CPU2: alive\r\n");
            }
        }
    }
}

/* This interrupt is raised by the STM0 */
IFX_INTERRUPT (updateLwIPStackISR, 2, ISR_PRIORITY_OS_TICK);

/* ISR to update LwIP stack */
void updateLwIPStackISR(void)
{
    /* Configure STM to generate an interrupt in 1 ms */
    IfxStm_increaseCompare(&MODULE_STM0, IfxStm_Comparator_0, IFX_CFG_STM_TICKS_PER_MS);

    g_TickCount_1ms++;                                      /* Increase LwIP system time                                    */

    Ifx_Lwip_onTimerTick();                                 /* Every 1 ms LwIP timers are increased for all the enabled
                                                             * protocols (ARP, TCP, DHCP, LINK)                             */
}
