/**********************************************************************************************************************
 * \file Cpu3_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxStm.h"
#include "UART_Logging.h"
#include <gtm/gtm.h>
#include <stdio.h>

extern IfxCpu_syncEvent g_cpuSyncEvent;

static void printGateDriverDataDuty(void);

void core3_main(void)
{
    uint64 lastPrintTick;
    uint64 printPeriodTicks;

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG3 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    initUART();
    lastPrintTick = (uint64)IfxStm_get(&MODULE_STM0);
    printPeriodTicks = (uint64)IfxStm_getTicksFromMilliseconds(&MODULE_STM0, 100U);

    while(1)
    {
        uint64 now = (uint64)IfxStm_get(&MODULE_STM0);

        if((now - lastPrintTick) >= printPeriodTicks)
        {
            lastPrintTick = now;
            printGateDriverDataDuty();
        }
    }
}

static void printGateDriverDataDuty(void)
{
    const GtmPwmInputMeasurement *measurement = gtmDriverDataTimGetMeasurement();
    char message[96];
    int len;
    uint32 dutyCentiPercent = 0U;

    if((measurement->initialized != FALSE) && (measurement->periodTicks > 0U))
    {
        dutyCentiPercent = (uint32)(((uint64)measurement->pulseTicks * 10000ULL) /
                                    (uint64)measurement->periodTicks);
    }

    len = snprintf(message,
                   sizeof(message),
                   "GD DATA duty=%u.%02u%% p=%lu h=%lu coh=%u lost=%u ovf=%u glitch=%u\r\n",
                   (unsigned int)(dutyCentiPercent / 100U),
                   (unsigned int)(dutyCentiPercent % 100U),
                   (unsigned long)measurement->periodTicks,
                   (unsigned long)measurement->pulseTicks,
                   (unsigned int)measurement->dataCoherent,
                   (unsigned int)measurement->dataLost,
                   (unsigned int)measurement->overflow,
                   (unsigned int)measurement->glitch);

    if(len > 0)
    {
        if((unsigned int)len >= sizeof(message))
        {
            len = (int)(sizeof(message) - 1U);
            message[len] = '\0';
        }

        sendUARTMessage(message, (Ifx_SizeT)len);
    }
}
