/**********************************************************************************************************************
 * \file math.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <foc_math.h>
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void FOC_ClarkeTransform(ThreePhase_t *input_abc, AlphaBeta_t *output_ab)
{
    // Ia = I_alpha
    output_ab->alpha = input_abc->a;

    // Ib = (-1/2)*I_alpha + (sqrt(3)/2)*I_beta
    // Rearranging for Alpha/Beta derivation:
    // I_beta = (1/sqrt(3)) * (Ia + 2*Ib)
    output_ab->beta = ONE_BY_SQRT3 * (input_abc->a + (2.0f * input_abc->b));
}

void FOC_InvClarkeTransform(AlphaBeta_t *input_ab, ThreePhase_t *output_abc)
{
    // Va = V_alpha
    output_abc->a = input_ab->alpha;

    // Vb = (-1/2) * V_alpha + (sqrt(3)/2) * V_beta
    output_abc->b = (-0.5f * input_ab->alpha) + (0.86602540378f * input_ab->beta);

    // Vc = (-1/2) * V_alpha - (sqrt(3)/2) * V_beta
    output_abc->c = (-0.5f * input_ab->alpha) - (0.86602540378f * input_ab->beta);
}

void FOC_ParkTransform(AlphaBeta_t *input_ab, DQ_t *output_dq, float32 sinTheta, float32 cosTheta)
{
    // Id = I_alpha * cos(theta) + I_beta * sin(theta)
    output_dq->d = (input_ab->alpha * cosTheta) + (input_ab->beta * sinTheta);

    // Iq = -I_alpha * sin(theta) + I_beta * cos(theta)
    output_dq->q = (-input_ab->alpha * sinTheta) + (input_ab->beta * cosTheta);
}

void FOC_InvParkTransform(DQ_t *input_dq, AlphaBeta_t *output_ab, float32 sinTheta, float32 cosTheta)
{
    // V_alpha = Vd * cos(theta) - Vq * sin(theta)
    output_ab->alpha = (input_dq->d * cosTheta) - (input_dq->q * sinTheta);

    // V_beta = Vd * sin(theta) + Vq * cos(theta)
    output_ab->beta = (input_dq->d * sinTheta) + (input_dq->q * cosTheta);
}

/*
 * SVPWM takes stationary V_alpha and V_beta and calculates the 3 duty cycles (tA, tB, tC).
 * This implementation includes zero sequence injection (centralization).
 */
void FOC_SVPWM(AlphaBeta_t *V_ab, ThreePhase_t *DutyCycles)
{
    float32 V_alpha = V_ab->alpha;
    float32 V_beta = V_ab->beta;
    float32 V_u, V_v, V_w;
    float32 V_max, V_min;
    float32 V_offset;

    // 1. Calculate the three virtual phase voltages (normalized)
    // V_u = V_beta * 0.0f + V_alpha
    V_u = V_alpha;

    // V_v = (-1/2) * V_alpha + (sqrt(3)/2) * V_beta
    V_v = (-0.5f * V_alpha) + (0.86602540378f * V_beta);

    // V_w = (-1/2) * V_alpha - (sqrt(3)/2) * V_beta
    V_w = (-0.5f * V_alpha) - (0.86602540378f * V_beta);

    // 2. Find min and max of the three-phase values
    // Using simple conditional logic is faster than calling fmax/fmin
    V_max = V_u;
    if (V_v > V_max) V_max = V_v;
    if (V_w > V_max) V_max = V_w;

    V_min = V_u;
    if (V_v < V_min) V_min = V_v;
    if (V_w < V_min) V_min = V_w;

    // 3. Calculate Zero Sequence Component (offset)
    // This centers the voltage vector to maximize output without over-modulation.
    // V_offset = -(V_max + V_min) / 2.0f
    V_offset = -0.5f * (V_max + V_min);

    // 4. Calculate final duty cycles (normalized 0 to 1.0)
    // D_u = V_u + V_offset
    DutyCycles->a = V_u + V_offset;
    DutyCycles->b = V_v + V_offset;
    DutyCycles->c = V_w + V_offset;

    // The outputs are now normalized from -0.5 to 0.5 (or 0 to 1.0 if offset is included)
    // Ensure all duties are shifted to a range of 0.0 to 1.0 (for PWM timer operation)
    // Since V_max - V_min <= 1.0 and |V_ab| <= V_max_magnitude, this step may be needed
    // depending on the SVPWM implementation. For the implementation above, the duty is:
    // D_x = (0.5 * V_x_star) + 0.5 where V_x_star is the output.
    // The duty is naturally centered around 0.5. Since the input V_d, V_q should be
    // limited to the inscribed circle (V_max_mag = 1.0/SQRT3), the outputs are typically
    // clamped here to prevent over-modulation.

    // Clamp the duties to prevent illegal states (optional but recommended)
    if (DutyCycles->a > 1.0f) DutyCycles->a = 1.0f;
    if (DutyCycles->a < 0.0f) DutyCycles->a = 0.0f;

    if (DutyCycles->b > 1.0f) DutyCycles->b = 1.0f;
    if (DutyCycles->b < 0.0f) DutyCycles->b = 0.0f;

    if (DutyCycles->c > 1.0f) DutyCycles->c = 1.0f;
    if (DutyCycles->c < 0.0f) DutyCycles->c = 0.0f;
}
