/**********************************************************************************************************************
 * \file lut.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef LUT_H_
#define LUT_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include <math.h>
#include "foc_math.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LUT_SIZE_BITS   10U                     /* 10 bits for index. Size = 2^10 = 1024 points */
#define LUT_SIZE        (1U << LUT_SIZE_BITS)   /* Total number of points in the table */
#define LUT_MASK        (LUT_SIZE - 1U)         /* Bitmask for fast index wrapping (1023) */

#define RAD_TO_INDEX    ((float32)LUT_SIZE / TWO_PI) /* Scale factor: Radians -> Index */
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern float32 SinCos_LUT[LUT_SIZE];
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/**
 * @brief Generates the Sine LUT at run-time using the MCU's FPU.
 * This should be called ONCE during system initialization.
 */
extern void FOC_InitializeSinCosLut(void);

/**
 * @brief Calculates Sin and Cos values using a Look-Up Table with Linear Interpolation.
 * This function should be called inside the high-frequency FOC ISR.
 * @param angle_rad Input electrical angle in Radians (must be wrapped 0 to 2*PI).
 * @param sinVal Pointer to store the calculated sine value.
 * @param cosVal Pointer to store the calculated cosine value.
 */
extern void FOC_GetSinCos_LUT(float32 angle_rad, float32 *sinVal, float32 *cosVal);

#endif /* LUT_H_ */
