/**********************************************************************************************************************
 * \file GTM_ATOM_3_Phase_Inverter_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "pwm.h"
#include "Ifx_Types.h"
#include "IfxGtm_Pwm.h"
#include "IfxPort.h"
#include "IfxPort_Pinmap.h"
#include <math.h>
#include "foc_math.h"
#include "stdio.h"
#include "adc.h"
#include <Port/Io/IfxPort_Io.h>


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NUM_OF_CHANNELS         (3)                                    /* Number of PWM complementary pairs          */
#define PWM_FREQUENCY           (20.0E3)                               /* PWM frequency in [Hz]                      */
#define ISR_PRIORITY_ATOM       (20)                                   /* Interrupt priority number                  */

/* Open Loop FOC Settings */
#define FOC_PWM_PERIOD          (1.0f / PWM_FREQUENCY)                 /* PWM Period in Seconds                      */
#define FOC_TWO_PI              (6.28318530718f)
#define OPEN_LOOP_SPEED_HZ      (25.0f)                                 /* Initial Rotation Speed (Hz electrical)     */
#define OPEN_LOOP_VOLTAGE       (0.13f)                                 /* Open Loop Amplitude (0.0 to 1.0)           */

#define PHASE_U_HS              &IfxGtm_ATOM1_0_TOUT0_P02_0_OUT        /* Pin which will be driven by the PWM, P02.0 */
#define PHASE_U_LS              &IfxGtm_ATOM1_0N_TOUT7_P02_7_OUT       /* Pin which will be driven by the PWM, P02.7 */
#define PHASE_V_HS              &IfxGtm_ATOM1_1_TOUT1_P02_1_OUT        /* Pin which will be driven by the PWM, P02.1 */
#define PHASE_V_LS              &IfxGtm_ATOM1_1N_TOUT4_P02_4_OUT       /* Pin which will be driven by the PWM, P02.4 */
#define PHASE_W_HS              &IfxGtm_ATOM1_2_TOUT2_P02_2_OUT        /* Pin which will be driven by the PWM, P02.2 */
#define PHASE_W_LS              &IfxGtm_ATOM1_2N_TOUT5_P02_5_OUT       /* Pin which will be driven by the PWM, P02.5 */

#define PHASE_U_DUTY            (0.0f)                                 /* Initial PWM duty cycle of phase U in [%]   */
#define PHASE_V_DUTY            (0.0f)                                 /* Initial PWM duty cycle of phase V in [%]   */
#define PHASE_W_DUTY            (0.0f)                                 /* Initial PWM duty cycle of phase W in [%]   */

#define LED                     &MODULE_P13, 0       /* LED which will be toggled in Interrupt Service Routine (ISR) */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
        IfxGtm_Pwm          pwm;                                /* PWM Driver handle                                 */
        IfxGtm_Pwm_Channel  channels[NUM_OF_CHANNELS];          /* Array containing channel data after configuration */
        float32             dutyCycles[NUM_OF_CHANNELS];        /* Duty Cycle values to hold (0-100%)                */
        IfxGtm_Pwm_DeadTime deadTimes[NUM_OF_CHANNELS];         /* Deadtimes                                         */
} GtmAtom3phInv;

typedef struct
{
        float32       electricalAngle;    /* Current electrical angle [rad] */
        float32       speedRefHz;         /* Target speed [Hz] */
        float32       voltageRef;         /* Target voltage amplitude [0.0 - 1.0] */
        DQ_t          v_dq;               /* Voltage in DQ frame */
        AlphaBeta_t   v_ab;               /* Voltage in AlphaBeta frame */
        ThreePhase_t  duty_3ph;           /* Calculated Duty Cycles (0.0 - 1.0) */
} GtmFocControl;

IFX_STATIC GtmAtom3phInv g_gtmAtom3phInv;
IFX_STATIC GtmFocControl g_focControl;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
void updateGtmAtom3phInvDuty(void);

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define the Interrupt Service Routine. */
IFX_INTERRUPT(interruptGtmAtom, 0, ISR_PRIORITY_ATOM);

/* Interrupt Service Routine of the ATOM - Executes Open Loop FOC */
void interruptGtmAtom(void)
{
    IfxPort_setPinHigh(&MODULE_P00, 12);

    float32 sinVal, cosVal;
    startEvadcConversion();
    /* 1. Update Electrical Angle */
    g_focControl.electricalAngle += (g_focControl.speedRefHz * FOC_TWO_PI * FOC_PWM_PERIOD);

    /* Wrap Angle (0 to 2PI) */
    if(g_focControl.electricalAngle >= FOC_TWO_PI)
    {
        g_focControl.electricalAngle -= FOC_TWO_PI;
    }
    else if(g_focControl.electricalAngle < 0.0f)
    {
        g_focControl.electricalAngle += FOC_TWO_PI;
    }

    /* 2. Set Reference Vector in DQ Frame (Open Loop: Vd=0, Vq=Target) */
    g_focControl.v_dq.d = 0.0f;
    g_focControl.v_dq.q = g_focControl.voltageRef;

    /* 3. Inverse Park Transform (DQ -> AlphaBeta) */
    sinVal = sinf(g_focControl.electricalAngle);
    cosVal = cosf(g_focControl.electricalAngle);
    FOC_InvParkTransform(&g_focControl.v_dq, &g_focControl.v_ab, sinVal, cosVal);

    /* 4. SVPWM (AlphaBeta -> 3-Phase Duty 0.0-1.0) */
    FOC_SVPWM(&g_focControl.v_ab, &g_focControl.duty_3ph);

    /* 5. Update Hardware (Convert 0.0-1.0 to 0-100%) */
    g_gtmAtom3phInv.dutyCycles[0] = g_focControl.duty_3ph.a * 100.0f; /* Phase U */
    g_gtmAtom3phInv.dutyCycles[1] = g_focControl.duty_3ph.b * 100.0f; /* Phase V */
    g_gtmAtom3phInv.dutyCycles[2] = g_focControl.duty_3ph.c * 100.0f; /* Phase W */

    /* Apply duties immediately */
    IfxGtm_Pwm_updateChannelsDutyImmediate(&g_gtmAtom3phInv.pwm, (float32*)g_gtmAtom3phInv.dutyCycles);

    //printf("%.2f;%.2f;%.2f\n", g_gtmAtom3phInv.dutyCycles[0], g_gtmAtom3phInv.dutyCycles[1], g_gtmAtom3phInv.dutyCycles[2]);

    /* Toggle LED for liveness check */
    IfxPort_togglePin(LED);

}

/* Period interrupt callback function */
void IfxGtm_periodEventFunction(void *data)
{
    /* Not used if ISR is handled directly via interruptGtmAtom logic above */
}

/* This function initializes the ATOM */
void initGtmAtom3phInv(void)
{
    initEvadc(); /* <--- 3. Call ADC Init */
    /* Initialize FOC variables */
    g_focControl.electricalAngle = 0.0f;
    g_focControl.speedRefHz      = OPEN_LOOP_SPEED_HZ;
    g_focControl.voltageRef      = OPEN_LOOP_VOLTAGE;

    /* Configuration variables */
    IfxGtm_Pwm_Config config;                                /* Main PWM configuration structure                     */
    IfxGtm_Pwm_ChannelConfig channelConfig[NUM_OF_CHANNELS]; /* Array containing configuration for each channel      */
    IfxGtm_Pwm_DtmConfig dtmConfig[NUM_OF_CHANNELS];         /* Only needed if using DTM module                      */
    IfxGtm_Pwm_InterruptConfig interruptConfig;              /* Only needed if using interrupt.                      */
    IfxGtm_Pwm_OutputConfig output[NUM_OF_CHANNELS];         /* Only needed if connected to pin                      */

    IfxGtm_Pwm_initConfig(&config, &MODULE_GTM);

    /* Output configuration */
    /* CH0 - Phase U (Note: Mapped to CH0 for logical consistency with array index 0) */
    output[0].pin                   = (IfxGtm_Pwm_ToutMap*)PHASE_U_HS;
    output[0].complementaryPin      = (IfxGtm_Pwm_ToutMap*)PHASE_U_LS;
    output[0].polarity              = Ifx_ActiveState_high;
    output[0].complementaryPolarity = Ifx_ActiveState_low;
    output[0].outputMode            = IfxPort_OutputMode_pushPull;
    output[0].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    /* CH1 - Phase V */
    output[1].pin                   = (IfxGtm_Pwm_ToutMap*)PHASE_V_HS;
    output[1].complementaryPin      = (IfxGtm_Pwm_ToutMap*)PHASE_V_LS;
    output[1].polarity              = Ifx_ActiveState_high;
    output[1].complementaryPolarity = Ifx_ActiveState_low;
    output[1].outputMode            = IfxPort_OutputMode_pushPull;
    output[1].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    /* CH2 - Phase W */
    output[2].pin                   = (IfxGtm_Pwm_ToutMap*)PHASE_W_HS;
    output[2].complementaryPin      = (IfxGtm_Pwm_ToutMap*)PHASE_W_LS;
    output[2].polarity              = Ifx_ActiveState_high;
    output[2].complementaryPolarity = Ifx_ActiveState_low;
    output[2].outputMode            = IfxPort_OutputMode_pushPull;
    output[2].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    /* Dead-time configuration */
    dtmConfig[0].deadTime.rising    = 1e-6f;
    dtmConfig[0].deadTime.falling   = 1e-6f;
    dtmConfig[1].deadTime.rising    = 1e-6f;
    dtmConfig[1].deadTime.falling   = 1e-6f;
    dtmConfig[2].deadTime.rising    = 1e-6f;
    dtmConfig[2].deadTime.falling   = 1e-6f;

    /* Interrupt configuration */
    interruptConfig.mode          = IfxGtm_IrqMode_pulseNotify;
    interruptConfig.isrProvider   = IfxSrc_Tos_cpu0;
    interruptConfig.priority      = ISR_PRIORITY_ATOM;
    interruptConfig.periodEvent   = IfxGtm_periodEventFunction;
    interruptConfig.dutyEvent     = NULL_PTR;

    /* Channel configuration */
    /* CH0 (Phase U) - Master for Sync */
    channelConfig[0].timerCh      = IfxGtm_Pwm_SubModule_Ch_0;
    channelConfig[0].phase        = 0.0f;
    channelConfig[0].duty         = PHASE_U_DUTY;
    channelConfig[0].dtm          = &dtmConfig[0];
    channelConfig[0].output       = &output[0];
    channelConfig[0].mscOut       = NULL_PTR;
    channelConfig[0].interrupt    = &interruptConfig; /* Interrupt enabled on this channel */

    /* CH1 (Phase V) */
    channelConfig[1].timerCh      = IfxGtm_Pwm_SubModule_Ch_1;
    channelConfig[1].phase        = 0.0f;
    channelConfig[1].duty         = PHASE_V_DUTY;
    channelConfig[1].dtm          = &dtmConfig[1];
    channelConfig[1].output       = &output[1];
    channelConfig[1].mscOut       = NULL_PTR;
    channelConfig[1].interrupt    = NULL_PTR;

    /* CH2 (Phase W) */
    channelConfig[2].timerCh      = IfxGtm_Pwm_SubModule_Ch_2;
    channelConfig[2].phase        = 0.0f;
    channelConfig[2].duty         = PHASE_W_DUTY;
    channelConfig[2].dtm          = &dtmConfig[2];
    channelConfig[2].output       = &output[2];
    channelConfig[2].mscOut       = NULL_PTR;
    channelConfig[2].interrupt    = NULL_PTR;

    /* Global GTM Config */
    config.cluster                = IfxGtm_Cluster_1;
    config.subModule              = IfxGtm_Pwm_SubModule_atom;
    config.alignment              = IfxGtm_Pwm_Alignment_center;
    config.syncStart              = TRUE;
    config.numChannels            = NUM_OF_CHANNELS;
    config.channels               = channelConfig;
    config.frequency              = PWM_FREQUENCY;
    config.clockSource.atom       = IfxGtm_Cmu_Clk_0;
    config.dtmClockSource         = IfxGtm_Dtm_ClockSource_cmuClock0;
    config.syncUpdateEnabled      = TRUE;

    if(!IfxGtm_isEnabled(&MODULE_GTM))
    {
        float32 frequency;
        IfxGtm_enable(&MODULE_GTM);
        frequency = IfxGtm_Cmu_getModuleFrequency(&MODULE_GTM);
        IfxGtm_Cmu_setGclkFrequency(&MODULE_GTM, frequency);
        IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, IfxGtm_Cmu_Clk_0, frequency);
        IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK0);
    }

    IfxGtm_Pwm_init(&g_gtmAtom3phInv.pwm, &g_gtmAtom3phInv.channels[0], &config);

    /* Store initial values */
    g_gtmAtom3phInv.dutyCycles[0]= channelConfig[0].duty;
    g_gtmAtom3phInv.dutyCycles[1]= channelConfig[1].duty;
    g_gtmAtom3phInv.dutyCycles[2]= channelConfig[2].duty;
    g_gtmAtom3phInv.deadTimes[0]= channelConfig[0].dtm->deadTime;
    g_gtmAtom3phInv.deadTimes[1]= channelConfig[1].dtm->deadTime;
    g_gtmAtom3phInv.deadTimes[2]= channelConfig[2].dtm->deadTime;

    IfxPort_setPinModeOutput(LED, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
}

/* This function can be used to change speed at runtime */
void updateGtmAtom3phInvDuty(void)
{
    /* Example: Ramp speed or change voltage here if needed by main loop */
}
