/**********************************************************************************************************************
 * \file lut.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "lut.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
float32 SinCos_LUT[LUT_SIZE];
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**
 * @brief Generates the Sine LUT at run-time using the MCU's FPU.
 * This should be called ONCE during system initialization.
 */
void FOC_InitializeSinCosLut(void)
{
    uint32 i;
    float32 angle_step = TWO_PI / (float32)LUT_SIZE;
    float32 angle = 0.0f;

    for (i = 0; i < LUT_SIZE; i++)
    {
        // Calculate the sine value using the TriCore's sinf() function
        SinCos_LUT[i] = sinf(angle);

        // Step to the next angle
        angle += angle_step;
    }
}

/**
 * @brief Calculates Sin and Cos values using a Look-Up Table with Linear Interpolation.
 * This function should be called inside the high-frequency FOC ISR.
 * Note: Use 'static inline' in the header for maximum performance, but defining it
 * as a standard function here provides better decoupling and debugging.
 */
void FOC_GetSinCos_LUT(float32 angle_rad, float32 *sinVal, float32 *cosVal)
{
    float32 exactIndex;
    uint32 idx_i;
    float32 frac;

    // 1. Scale angle (Radians) to Table Index
    // (Assuming angle_rad is already wrapped 0 <= angle_rad < TWO_PI)
    exactIndex = angle_rad * RAD_TO_INDEX;

    // 2. Separate Integer (idx_i) and Fractional (frac) parts
    idx_i = (uint32)exactIndex;
    frac  = exactIndex - (float32)idx_i;

    // --- SINE CALCULATION (Interpolation) ---
    uint32 idx_sin_0 = idx_i & LUT_MASK;
    uint32 idx_sin_1 = (idx_i + 1U) & LUT_MASK;

    float32 sin_y0 = SinCos_LUT[idx_sin_0];
    float32 sin_y1 = SinCos_LUT[idx_sin_1];

    // Linear Interpolation: y = y0 + (y1 - y0) * frac
    *sinVal = sin_y0 + (frac * (sin_y1 - sin_y0));

    // --- COSINE CALCULATION (90-degree shift and Interpolation) ---
    uint32 offset = LUT_SIZE >> 2; // LUT_SIZE / 4

    uint32 idx_cos_0 = (idx_i + offset) & LUT_MASK;
    uint32 idx_cos_1 = (idx_cos_0 + 1U) & LUT_MASK;

    float32 cos_c0 = SinCos_LUT[idx_cos_0];
    float32 cos_c1 = SinCos_LUT[idx_cos_1];

    *cosVal = cos_c0 + (frac * (cos_c1 - cos_c0));
}
